name: Devops

env:
  PIP_BREAK_SYSTEM_PACKAGES: "1"
  DEBIAN_FRONTEND: "noninteractive"

on:
  workflow_dispatch:
    inputs:
  schedule:
    - cron: '*/20 * * * *'
  
jobs:
  main:
    runs-on: debian-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup
      run: |

        sudo apt-get update && sudo apt-get install -y curl git jq bash ssh python3 python3-pip

        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"

        echo "$(date '+%w')" | sha256sum  > digest
        git add digest
        nohup bash -c "git commit -m 'resource update' && git push" >/dev/null 2>&1 &

    - name: Update
      run: |
        printf '%s' "${{ secrets.config }}" | base64 -d | sudo bash
